### ISSUE TITLE
Offer software in popular package formats

### ISSUE THREAD

**Issue by elfring** [formiaczek/multi_key_dict#6]
Would you like to offer your class library as a software package in formats like the following?
* [DEB](https://en.wikipedia.org/wiki/Deb_%28file_format%29 "DEB package format")
* [RPM](https://en.wikipedia.org/wiki/RPM_Package_Manager#Format "RPM package format")

**Comment by jsbueno** [comment]
What would be the purpose of that? 
Python users can install this with "pip install ..." - and it will work not only cross linux-distributions, but in all platforms were Python runs.  The overhead of packaging DEB and RPM files is not small, and they are only convenient if they are available at the default (or at a popular) repository for each specific Linux distribution.

(At which point the distribution maintainers should package it to the Linux distro native type, not the package author).  Having to download a ".deb" or ".rpm" to manually install it, without using a repository is much more cumbersome than using "pip install", and having to add a repository just for a single utility Python module doubles the cumbersomeness. 

+1 for closing this issue

**Comment by formiaczek** [comment]
Thanks jsbueno. I initialy thought that doing this would be ok, but I agree with you - it kind-of doesn't make too much sense really.

I'll wait few days if elfring will have any comments and close it.

+1 for commenting it  :+1:

**Comment by elfring** [comment]
How useful do you find related package management tools generally?

Can [the Pip interface](https://en.wikipedia.org/wiki/Pip_%28package_manager%29 "Package management for Python") cooperate with other well-known approaches?

**Comment by formiaczek** [comment]
Which well-know approaches do you have in mind?

I find them useful. You can use it directly with the github repository - see https://pip.pypa.io/en/latest/reference/pip_install.html#vcs-support. Otherwise, standard packages are easy to distribute and integrate - see https://docs.python.org/2/distutils/. Whilst it's easy to create an RPM, I did not find examples of creating .deb packages with python modules, thus I did't publish it on pypi.

**Comment by elfring** [comment]
I guess that it will matter occasionally which package database will be the primary interface for your software, won't it?

**Comment by formiaczek** [comment]
Closing the issue: pypi interface / distribution should suffice for now.
